/**
 * Direct unit tests for OfflineQueue and idempotency behaviour.
 *
 * Covers:
 *  #261 – startup race: enqueue() before storage load must not lose entries
 *  #262 – idempotency key added to QueueEntry and forwarded on replay
 *  #263 – replay, onDrained, clearQueue, setOnline, StorageAdapter round-trip
 *  #264 – non-idempotent POST retries in BridgeClient carry idempotency key
 */

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { OfflineQueue } from '../src/offline';
import { BridgeClient } from '../src/bridge';
import { QueueEntry, StorageAdapter } from '../src/types';

// ─── Helpers ─────────────────────────────────────────────────────────────────

/** Minimal in-memory StorageAdapter for tests. */
function makeStorage(): StorageAdapter & { store: Map<string, string> } {
  const store = new Map<string, string>();
  return {
    store,
    async get(key) { return store.get(key) ?? null; },
    async set(key, value) { store.set(key, value); },
    async remove(key) { store.delete(key); },
  };
}

/** A storage adapter whose get() resolves only after a tick, simulating async I/O. */
function makeSlowStorage(delayMs = 10): StorageAdapter & { store: Map<string, string> } {
  const store = new Map<string, string>();
  return {
    store,
    async get(key) {
      await new Promise((r) => setTimeout(r, delayMs));
      return store.get(key) ?? null;
    },
    async set(key, value) { store.set(key, value); },
    async remove(key) { store.delete(key); },
  };
}

/** A base QueueEntry fixture (without the fields generated by enqueue). */
const BASE_ENTRY: Omit<QueueEntry, 'id' | 'timestamp' | 'retryCount'> = {
  method: 'GET',
  path: '/api/v1/status/test',
};

const POST_ENTRY: Omit<QueueEntry, 'id' | 'timestamp' | 'retryCount'> = {
  method: 'POST',
  path: '/api/v1/cex/route',
  body: { exchange: 'binance', amount: '1000' },
};

// ─── OfflineQueue — enqueue / getQueue ──────────────────────────────────────

describe('OfflineQueue — enqueue and getQueue', () => {
  it('enqueues an entry and returns its id', async () => {
    const q = new OfflineQueue(vi.fn(), vi.fn(), { healthCheckIntervalMs: 60_000 });
    const id = await q.enqueue(BASE_ENTRY);
    expect(typeof id).toBe('string');
    expect(id.length).toBeGreaterThan(0);
    q.destroy();
  });

  it('getQueue returns a snapshot (not the internal reference)', async () => {
    const q = new OfflineQueue(vi.fn(), vi.fn(), { healthCheckIntervalMs: 60_000 });
    await q.enqueue(BASE_ENTRY);
    const snap1 = q.getQueue();
    await q.enqueue(BASE_ENTRY);
    const snap2 = q.getQueue();
    // snap1 was taken before the second enqueue — it must not change
    expect(snap1).toHaveLength(1);
    expect(snap2).toHaveLength(2);
    q.destroy();
  });

  it('throws QueueFullError when max capacity is reached', async () => {
    const q = new OfflineQueue(vi.fn(), vi.fn(), { maxSize: 2, healthCheckIntervalMs: 60_000 });
    await q.enqueue(BASE_ENTRY);
    await q.enqueue(BASE_ENTRY);
    await expect(q.enqueue(BASE_ENTRY)).rejects.toThrow(/queue.*full/i);
    q.destroy();
  });
});

// ─── OfflineQueue — clearQueue ───────────────────────────────────────────────

describe('OfflineQueue — clearQueue', () => {
  it('empties the in-memory queue', async () => {
    const q = new OfflineQueue(vi.fn(), vi.fn(), { healthCheckIntervalMs: 60_000 });
    await q.enqueue(BASE_ENTRY);
    await q.enqueue(BASE_ENTRY);
    await q.clearQueue();
    expect(q.getQueue()).toHaveLength(0);
    q.destroy();
  });

  it('removes persisted data from storage', async () => {
    const storage = makeStorage();
    const q = new OfflineQueue(vi.fn(), vi.fn(), {
      storageAdapter: storage,
      healthCheckIntervalMs: 60_000,
    });
    await q.enqueue(BASE_ENTRY);
    expect(storage.store.size).toBe(1); // persisted
    await q.clearQueue();
    expect(storage.store.size).toBe(0); // cleared
    q.destroy();
  });
});

// ─── OfflineQueue — replay ────────────────────────────────────────────────────

describe('OfflineQueue — replay via setOnline', () => {
  it('executes all queued entries when coming back online', async () => {
    const execute = vi.fn().mockResolvedValue(undefined);
    const q = new OfflineQueue(execute, vi.fn(), { healthCheckIntervalMs: 60_000 });
    q.setOnline(false); // mark offline
    await q.enqueue(BASE_ENTRY);
    await q.enqueue(BASE_ENTRY);
    expect(q.getQueue()).toHaveLength(2);

    q.setOnline(true); // triggers replay
    // Allow microtasks / promises to flush
    await new Promise((r) => setTimeout(r, 20));

    expect(execute).toHaveBeenCalledTimes(2);
    expect(q.getQueue()).toHaveLength(0);
    q.destroy();
  });

  it('keeps entries that fail during replay (increments retryCount)', async () => {
    let callCount = 0;
    const execute = vi.fn().mockImplementation(() => {
      if (callCount++ === 0) throw new Error('transient');
      return Promise.resolve();
    });
    const q = new OfflineQueue(execute, vi.fn(), { healthCheckIntervalMs: 60_000 });
    q.setOnline(false);
    await q.enqueue(BASE_ENTRY);
    await q.enqueue(BASE_ENTRY);

    q.setOnline(true);
    await new Promise((r) => setTimeout(r, 20));

    // First entry failed, second succeeded → one remains
    expect(q.getQueue()).toHaveLength(1);
    expect(q.getQueue()[0].retryCount).toBe(1);
    q.destroy();
  });

  it('does not replay when already replaying (re-entrancy guard)', async () => {
    let resolveFn: () => void;
    const blockingExecute = vi.fn().mockImplementation(
      () => new Promise<void>((r) => { resolveFn = r; }),
    );
    const q = new OfflineQueue(blockingExecute, vi.fn(), { healthCheckIntervalMs: 60_000 });
    q.setOnline(false);
    await q.enqueue(BASE_ENTRY);

    q.setOnline(true); // starts replay (blocking)
    q.setOnline(false);
    q.setOnline(true); // second trigger — should be a no-op while replaying

    resolveFn!();
    await new Promise((r) => setTimeout(r, 20));

    // execute should only have been called once despite two setOnline(true) calls
    expect(blockingExecute).toHaveBeenCalledTimes(1);
    q.destroy();
  });
});

// ─── OfflineQueue — onDrained ─────────────────────────────────────────────────

describe('OfflineQueue — onDrained', () => {
  it('fires drain handler with processed count and ISO timestamp', async () => {
    const execute = vi.fn().mockResolvedValue(undefined);
    const q = new OfflineQueue(execute, vi.fn(), { healthCheckIntervalMs: 60_000 });
    const handler = vi.fn();
    q.onDrained(handler);

    q.setOnline(false);
    await q.enqueue(BASE_ENTRY);
    await q.enqueue(BASE_ENTRY);
    q.setOnline(true);
    await new Promise((r) => setTimeout(r, 20));

    expect(handler).toHaveBeenCalledTimes(1);
    const [count, at] = handler.mock.calls[0] as [number, string];
    expect(count).toBe(2);
    expect(() => new Date(at)).not.toThrow();
  });

  it('does not fire drain handler when no entries were processed', async () => {
    const execute = vi.fn().mockRejectedValue(new Error('always fails'));
    const q = new OfflineQueue(execute, vi.fn(), { healthCheckIntervalMs: 60_000 });
    const handler = vi.fn();
    q.onDrained(handler);

    q.setOnline(false);
    await q.enqueue(BASE_ENTRY);
    q.setOnline(true);
    await new Promise((r) => setTimeout(r, 20));

    expect(handler).not.toHaveBeenCalled();
    q.destroy();
  });

  it('supports multiple drain handlers', async () => {
    const execute = vi.fn().mockResolvedValue(undefined);
    const q = new OfflineQueue(execute, vi.fn(), { healthCheckIntervalMs: 60_000 });
    const h1 = vi.fn();
    const h2 = vi.fn();
    q.onDrained(h1);
    q.onDrained(h2);

    q.setOnline(false);
    await q.enqueue(BASE_ENTRY);
    q.setOnline(true);
    await new Promise((r) => setTimeout(r, 20));

    expect(h1).toHaveBeenCalledTimes(1);
    expect(h2).toHaveBeenCalledTimes(1);
    q.destroy();
  });
});

// ─── OfflineQueue — setOnline ─────────────────────────────────────────────────

describe('OfflineQueue — setOnline', () => {
  it('does not replay when already online', async () => {
    const execute = vi.fn().mockResolvedValue(undefined);
    const q = new OfflineQueue(execute, vi.fn(), { healthCheckIntervalMs: 60_000 });
    // Start online (default); add an entry while online (would not normally happen
    // but proves setOnline(true) when already online is a no-op for replay)
    await q.enqueue(BASE_ENTRY);
    q.setOnline(true); // no-op — was already online
    await new Promise((r) => setTimeout(r, 20));
    expect(execute).not.toHaveBeenCalled();
    q.destroy();
  });

  it('offline → online transition triggers replay', async () => {
    const execute = vi.fn().mockResolvedValue(undefined);
    const q = new OfflineQueue(execute, vi.fn(), { healthCheckIntervalMs: 60_000 });
    q.setOnline(false);
    await q.enqueue(BASE_ENTRY);
    q.setOnline(true);
    await new Promise((r) => setTimeout(r, 20));
    expect(execute).toHaveBeenCalledTimes(1);
    q.destroy();
  });
});

// ─── OfflineQueue — StorageAdapter persistence round-trip ────────────────────

describe('OfflineQueue — StorageAdapter persistence', () => {
  it('persists enqueued entries to storage', async () => {
    const storage = makeStorage();
    const q = new OfflineQueue(vi.fn(), vi.fn(), {
      storageAdapter: storage,
      healthCheckIntervalMs: 60_000,
    });
    await q.enqueue(BASE_ENTRY);
    expect(storage.store.size).toBe(1);
    const stored = JSON.parse(storage.store.values().next().value as string) as QueueEntry[];
    expect(stored).toHaveLength(1);
    expect(stored[0].path).toBe(BASE_ENTRY.path);
    q.destroy();
  });

  it('loads persisted entries on construction', async () => {
    const storage = makeStorage();
    const existing: QueueEntry[] = [
      { id: 'pre-1', timestamp: new Date().toISOString(), retryCount: 0, method: 'GET', path: '/loaded' },
    ];
    storage.store.set('bridge_sdk_offline_queue', JSON.stringify(existing));

    const q = new OfflineQueue(vi.fn(), vi.fn(), {
      storageAdapter: storage,
      healthCheckIntervalMs: 60_000,
    });
    // Wait for the async storage load to complete
    await new Promise((r) => setTimeout(r, 20));

    const entries = q.getQueue();
    expect(entries).toHaveLength(1);
    expect(entries[0].id).toBe('pre-1');
    q.destroy();
  });

  it('updates storage after successful replay', async () => {
    const storage = makeStorage();
    const execute = vi.fn().mockResolvedValue(undefined);
    const q = new OfflineQueue(execute, vi.fn(), {
      storageAdapter: storage,
      healthCheckIntervalMs: 60_000,
    });
    q.setOnline(false);
    await q.enqueue(BASE_ENTRY);
    q.setOnline(true);
    await new Promise((r) => setTimeout(r, 20));

    const stored = JSON.parse(storage.store.values().next().value as string) as QueueEntry[];
    expect(stored).toHaveLength(0); // replayed and cleared
    q.destroy();
  });
});

// ─── #261 — Startup race condition ────────────────────────────────────────────

describe('#261 — startup race: enqueue before storage load completes', () => {
  it('does not lose entries enqueued before storage load resolves', async () => {
    const storage = makeSlowStorage(30); // 30 ms delay simulates async I/O
    const preloaded: QueueEntry[] = [
      { id: 'stored-1', timestamp: new Date().toISOString(), retryCount: 0, method: 'GET', path: '/stored' },
    ];
    storage.store.set('bridge_sdk_offline_queue', JSON.stringify(preloaded));

    const q = new OfflineQueue(vi.fn(), vi.fn(), {
      storageAdapter: storage,
      healthCheckIntervalMs: 60_000,
    });

    // enqueue() immediately, before the 30 ms storage load finishes
    const id = await q.enqueue({ method: 'POST', path: '/api/v1/fund', body: { signedXdr: 'AAAA' } });

    // Now wait for storage load to finish
    await new Promise((r) => setTimeout(r, 50));

    const entries = q.getQueue();
    const ids = entries.map((e) => e.id);

    // Both the in-memory entry and the stored entry must be present
    expect(ids).toContain(id);
    expect(ids).toContain('stored-1');
    expect(entries).toHaveLength(2);
    q.destroy();
  });
});

// ─── #262 — Idempotency key in QueueEntry ─────────────────────────────────────

describe('#262 — idempotency key in QueueEntry', () => {
  it('assigns an idempotency key to non-idempotent POST entries', async () => {
    const q = new OfflineQueue(vi.fn(), vi.fn(), { healthCheckIntervalMs: 60_000 });
    await q.enqueue(POST_ENTRY); // /api/v1/cex/route is non-idempotent
    const entry = q.getQueue()[0];
    expect(typeof entry.idempotencyKey).toBe('string');
    expect(entry.idempotencyKey!.length).toBeGreaterThan(0);
    q.destroy();
  });

  it('does not assign an idempotency key to GET entries', async () => {
    const q = new OfflineQueue(vi.fn(), vi.fn(), { healthCheckIntervalMs: 60_000 });
    await q.enqueue(BASE_ENTRY);
    const entry = q.getQueue()[0];
    expect(entry.idempotencyKey).toBeUndefined();
    q.destroy();
  });

  it('preserves a caller-supplied idempotency key', async () => {
    const q = new OfflineQueue(vi.fn(), vi.fn(), { healthCheckIntervalMs: 60_000 });
    await q.enqueue({ ...POST_ENTRY, idempotencyKey: 'my-key-abc' });
    expect(q.getQueue()[0].idempotencyKey).toBe('my-key-abc');
    q.destroy();
  });

  it('sends the same idempotency key on replay as was stored', async () => {
    const capturedKeys: (string | undefined)[] = [];
    const execute = vi.fn().mockImplementation((entry: QueueEntry) => {
      capturedKeys.push(entry.idempotencyKey);
      return Promise.resolve();
    });

    const q = new OfflineQueue(execute, vi.fn(), { healthCheckIntervalMs: 60_000 });
    q.setOnline(false);
    await q.enqueue(POST_ENTRY);

    const originalKey = q.getQueue()[0].idempotencyKey;
    expect(typeof originalKey).toBe('string');

    q.setOnline(true);
    await new Promise((r) => setTimeout(r, 20));

    // The key forwarded to executeEntry must match the stored key
    expect(capturedKeys[0]).toBe(originalKey);
    q.destroy();
  });

  it('generates a unique idempotency key for each separate enqueue call', async () => {
    const q = new OfflineQueue(vi.fn(), vi.fn(), { healthCheckIntervalMs: 60_000 });
    await q.enqueue(POST_ENTRY);
    await q.enqueue(POST_ENTRY);
    const [a, b] = q.getQueue();
    expect(a.idempotencyKey).toBeTruthy();
    expect(b.idempotencyKey).toBeTruthy();
    expect(a.idempotencyKey).not.toBe(b.idempotencyKey);
    q.destroy();
  });
});

// ─── #264 — BridgeClient adds idempotency key to non-idempotent POST retries ──

describe('#264 — BridgeClient idempotency key on POST retries', () => {
  afterEach(() => {
    vi.restoreAllMocks();
  });

  it('includes Idempotency-Key header on first attempt of a non-idempotent POST', async () => {
    const client = new BridgeClient({
      baseUrl: 'http://localhost:3001',
      retry: { maxRetries: 0 },
    });

    vi.stubGlobal('fetch', vi.fn().mockResolvedValueOnce({
      ok: true,
      json: () => Promise.resolve({ status: 'pending', withdrawalId: 'wd-1' }),
    }));

    await client.routeCexWithdrawal({
      exchange: 'binance',
      sourceAsset: 'XLM',
      amount: '1000',
      targetCAddress: 'CABCDEFGHIJKLMNOPQRSTUVWXYZ234567ABCDEFGHIJKLMNOPQRSTUVW',
    });

    const calledHeaders = (fetch as ReturnType<typeof vi.fn>).mock.calls[0][1].headers as Record<string, string>;
    expect(calledHeaders['Idempotency-Key']).toBeTruthy();
  });

  it('sends the same Idempotency-Key on retry as on the first attempt', async () => {
    const client = new BridgeClient({
      baseUrl: 'http://localhost:3001',
      retry: { maxRetries: 1, baseDelayMs: 0, jitterMs: 0 },
    });

    // First call → 503 (retryable), second call → 200
    vi.stubGlobal('fetch', vi.fn()
      .mockResolvedValueOnce({
        ok: false,
        status: 503,
        json: () => Promise.resolve({ message: 'Service Unavailable' }),
      })
      .mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve({ status: 'pending', withdrawalId: 'wd-2' }),
      }),
    );

    await client.routeCexWithdrawal({
      exchange: 'binance',
      sourceAsset: 'XLM',
      amount: '1000',
      targetCAddress: 'CABCDEFGHIJKLMNOPQRSTUVWXYZ234567ABCDEFGHIJKLMNOPQRSTUVW',
    });

    const fetchMock = fetch as ReturnType<typeof vi.fn>;
    expect(fetchMock).toHaveBeenCalledTimes(2);

    const firstKey = (fetchMock.mock.calls[0][1].headers as Record<string, string>)['Idempotency-Key'];
    const secondKey = (fetchMock.mock.calls[1][1].headers as Record<string, string>)['Idempotency-Key'];

    expect(firstKey).toBeTruthy();
    expect(firstKey).toBe(secondKey); // same key on retry
  });

  it('sends the same Idempotency-Key for createMoonpayUrl retries', async () => {
    const client = new BridgeClient({
      baseUrl: 'http://localhost:3001',
      retry: { maxRetries: 1, baseDelayMs: 0, jitterMs: 0 },
    });

    vi.stubGlobal('fetch', vi.fn()
      .mockResolvedValueOnce({
        ok: false,
        status: 503,
        json: () => Promise.resolve({ message: 'Service Unavailable' }),
      })
      .mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve({ url: 'https://buy.moonpay.com?test=1' }),
      }),
    );

    await client.createMoonpayUrl({ walletAddress: 'CABCDEFGHIJKLMNOPQRSTUVWXYZ234567ABCDEFGHIJKLMNOPQRSTUVW' });

    const fetchMock = fetch as ReturnType<typeof vi.fn>;
    const firstKey = (fetchMock.mock.calls[0][1].headers as Record<string, string>)['Idempotency-Key'];
    const secondKey = (fetchMock.mock.calls[1][1].headers as Record<string, string>)['Idempotency-Key'];
    expect(firstKey).toBe(secondKey);
  });

  it('sends the same Idempotency-Key for createTransakUrl retries', async () => {
    const client = new BridgeClient({
      baseUrl: 'http://localhost:3001',
      retry: { maxRetries: 1, baseDelayMs: 0, jitterMs: 0 },
    });

    vi.stubGlobal('fetch', vi.fn()
      .mockResolvedValueOnce({
        ok: false,
        status: 503,
        json: () => Promise.resolve({ message: 'Service Unavailable' }),
      })
      .mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve({ url: 'https://global.transak.com?test=1' }),
      }),
    );

    await client.createTransakUrl({ walletAddress: 'CABCDEFGHIJKLMNOPQRSTUVWXYZ234567ABCDEFGHIJKLMNOPQRSTUVW' });

    const fetchMock = fetch as ReturnType<typeof vi.fn>;
    const firstKey = (fetchMock.mock.calls[0][1].headers as Record<string, string>)['Idempotency-Key'];
    const secondKey = (fetchMock.mock.calls[1][1].headers as Record<string, string>)['Idempotency-Key'];
    expect(firstKey).toBe(secondKey);
  });

  it('does not add Idempotency-Key to GET requests', async () => {
    const client = new BridgeClient({
      baseUrl: 'http://localhost:3001',
      retry: { maxRetries: 0 },
    });

    vi.stubGlobal('fetch', vi.fn().mockResolvedValueOnce({
      ok: true,
      json: () => Promise.resolve({ status: 'ok' }),
    }));

    await client.health();

    const calledHeaders = (fetch as ReturnType<typeof vi.fn>).mock.calls[0][1].headers as Record<string, string>;
    expect(calledHeaders['Idempotency-Key']).toBeUndefined();
  });
});
